services:
  - type: web
    name: weatherbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 5001
    # Secrets should be set in the Render Dashboard
    envVarsGroups:
      - name: weatherbot-secrets
        branch: main
      - key: DATABASE_URL
        value: sqlite:///weather.db 