services:
  - type: web
    name: weatherbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 5001
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///weather.db 